# Generated by Django 5.0.6 on 2024-07-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0002_slot_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
