# Generated by Django 5.0.6 on 2024-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0007_remove_profile_bio_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='profile'),
        ),
    ]
