# Generated by Django 5.0.6 on 2024-07-19 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0009_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/default_profile_image.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')]),
        ),
    ]
