# Generated by Django 5.0.6 on 2024-07-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0010_alter_profile_image_alter_profile_phone_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('sport_type', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football')], max_length=10)),
                ('max_players', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=120, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='turfapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
