# Generated by Django 5.0.6 on 2024-07-19 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0011_match_matchbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='turfapp.MatchBooking', to=settings.AUTH_USER_MODEL),
        ),
    ]
