# Generated by Django 5.0.6 on 2024-07-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0015_profile_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
