# Generated by Django 5.0.6 on 2024-07-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0016_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('COD', 'Cash on Delivery')], default='RAZORPAY', max_length=10),
        ),
    ]
