# Generated by Django 5.0.6 on 2024-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfapp', '0017_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('COD', 'Cash on Delivery')], default='COD', max_length=10),
        ),
    ]
